import React from 'react'

function Baitap6() {
    return (
        <div className='w-[500px] h-[200px] overflow-auto '>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, sint? Quis enim vitae ratione, aperiam commodi, mollitia magnam deleniti reiciendis corporis sed, eum repudiandae autem explicabo quam architecto quia cum!
            Dignissimos porro eos odio dolorem ullam dicta facere, ducimus, aspernatur perferendis unde quo, officia sit perspiciatis cumque rem consequatur in aut molestias? Aspernatur culpa nobis eaque quibusdam enim ducimus dolorum.
            Nobis fugiat est laboriosam dignissimos rerum omnis aliquam voluptate maxime facilis. Ipsam accusamus facere ratione nulla a vero, eum praesentium beatae corrupti molestiae nihil, excepturi eius dolor, consequuntur soluta adipisci.
            Numquam est beatae, corrupti quisquam culpa odit quasi unde architecto natus incidunt. Officiis reprehenderit quibusdam suscipit, aperiam rem reiciendis doloribus aspernatur mollitia corporis sed error voluptate recusandae deleniti architecto molestias!
            Unde similique culpa, vero reiciendis labore assumenda dolore sint harum, quibusdam atque sequi officiis possimus id facilis, amet iure ullam maxime deleniti quisquam quasi totam. Numquam explicabo accusantium doloremque dolorum.
            Repellat doloribus culpa dignissimos in voluptatibus, odio voluptatum, commodi, ratione ex veniam atque iure porro! Dicta atque tenetur quod, id cupiditate, iste dolores culpa inventore animi quibusdam, cum magni eos.
            Dolorem, quod enim assumenda sapiente atque iste illo libero quis commodi, iusto voluptatibus quas corporis cumque. Asperiores est voluptatem cupiditate voluptatum iste perspiciatis recusandae, quas suscipit tenetur optio culpa distinctio.
            Perspiciatis consequuntur maxime error earum itaque, adipisci esse odio eius atque. Modi incidunt, deleniti suscipit adipisci sed facere deserunt id eius pariatur? Quam suscipit corrupti ipsa mollitia ab harum voluptates.
            Autem itaque nihil veniam explicabo doloremque facere aliquid alias, tempora cum deserunt et eius provident maiores voluptatibus facilis praesentium ab tenetur soluta? Aliquid quaerat quisquam autem, similique officia exercitationem nemo?
            Quis quod soluta ratione, illum totam fuga saepe laboriosam voluptas obcaecati maiores sapiente eaque quibusdam fugiat. Qui ex molestiae dolorum nemo neque accusamus ea, distinctio minima. Nam eos modi vitae?
            Amet numquam vel labore quo aliquid laborum enim commodi animi impedit repellat laboriosam consequuntur ipsam omnis tempora minus aut earum voluptatem placeat, in est nulla quis ratione quisquam. Officia, quo.
            Ullam animi numquam maxime voluptates saepe praesentium fugit deleniti nobis dicta ipsam, illum id velit rem veritatis labore. Saepe nihil deserunt consequatur odio commodi consequuntur maxime amet ea quo distinctio.
            In autem beatae magni dolor nesciunt vel aperiam pariatur odio praesentium impedit consequuntur modi soluta doloremque architecto voluptates nobis recusandae aspernatur laborum dignissimos consequatur vitae, saepe eum sint nulla. Corporis.
            Cum incidunt, reiciendis non fugiat corrupti accusamus officiis consequuntur voluptatum obcaecati quo, nulla quae inventore tempore impedit temporibus fugit, at numquam libero odit dolorem minus voluptas. Illum asperiores rerum nihil!
            Repellendus tenetur nobis earum. Voluptatem fugiat veniam, amet consequuntur quas repudiandae voluptatum harum ipsa earum accusantium provident odio eius ex, architecto, adipisci vel totam hic praesentium est ad. Quos, sunt!
            Repellat facilis modi dolore unde similique laboriosam perferendis sed amet corporis sit, ratione adipisci quos veritatis laborum animi repellendus accusamus nobis eos voluptatum ut necessitatibus delectus? Amet fuga magnam reiciendis.
            Voluptatibus incidunt aspernatur cum ex, delectus cumque quis possimus sequi laudantium blanditiis tempora, quam ab ipsum? Nemo sunt similique, enim sed repellat sit id quo quia aut perferendis laboriosam accusamus.
            Obcaecati corrupti aspernatur ipsam maxime, exercitationem quidem voluptate ab ex. Quisquam iure quam id odit vitae numquam, similique magni magnam, doloribus maiores debitis repudiandae dolorum labore asperiores animi eius officia!
            Assumenda tenetur, deserunt nostrum vitae optio perspiciatis sequi ipsam consequuntur illo, distinctio sint nihil atque quis dolor aliquid commodi, debitis dolore minima at nisi obcaecati fuga enim beatae vel. Perspiciatis!
            Consequuntur est ab dicta officiis, nesciunt minus a nobis alias animi sunt tenetur vitae tempora rem explicabo quae cupiditate voluptates at totam, architecto porro! Atque id nisi odio assumenda quaerat.
            Error laboriosam eius qui obcaecati laborum rerum vitae quae. Vero voluptates consequuntur temporibus quo nesciunt asperiores, nobis sit animi ipsum? Accusantium harum natus atque doloribus temporibus. Minus perspiciatis soluta reprehenderit.
            Reiciendis neque aut dicta rerum quis reprehenderit ipsa ea enim unde, quia excepturi cumque cum vitae, sed eligendi in aspernatur recusandae numquam modi suscipit voluptatum. Nulla veniam nemo minima cupiditate.
            Iste eius recusandae nostrum fugit deleniti. Cum ad obcaecati neque sequi blanditiis provident velit mollitia officia necessitatibus? Corrupti illo a placeat non voluptatem laborum, dolorem adipisci autem, sapiente delectus sed.
            Harum ut voluptates dolore neque blanditiis mollitia ab? Nemo quisquam reprehenderit modi! Rem nulla, modi cum aliquam porro temporibus exercitationem quasi? Quibusdam deserunt debitis expedita enim. Eaque, illum est. Ipsam!
            Molestias amet sed atque culpa libero itaque adipisci, incidunt ut recusandae cumque ab vel eligendi dolor totam veritatis mollitia, architecto eum assumenda omnis. Quisquam ea provident mollitia nesciunt fuga natus?
            Illum molestias voluptas minima quibusdam, optio nobis, et, quam eos asperiores voluptatum assumenda hic dicta necessitatibus architecto eaque itaque labore tenetur sunt officiis? Minima earum, quas sunt alias ut nisi.
            Totam voluptate deleniti adipisci neque quisquam reprehenderit at voluptatem eligendi sunt, vel pariatur necessitatibus blanditiis sed, placeat expedita sit veritatis in rem maiores quo earum voluptates temporibus. Accusamus, assumenda maxime.
            Repellat sunt earum possimus non omnis impedit ab aut excepturi cupiditate expedita ipsa illum voluptatem velit, eius aliquid laboriosam! Aliquam vel saepe atque minus corrupti? Soluta consequatur delectus perferendis incidunt!
            Maxime, perspiciatis consequatur libero eos maiores hic labore illum, ducimus laborum soluta, tenetur ut dolore. Quidem nostrum quod aperiam ipsa harum animi, sint ratione cupiditate voluptatum id veritatis, qui possimus?
            Perferendis, vero rem! Rerum ipsam suscipit explicabo maxime ullam nemo quae voluptatibus officiis corporis dolor error fuga amet modi nobis, illo nam! Ipsum, sequi. Ipsam commodi soluta pariatur dicta eos.
            At consectetur illo optio ipsam nam odit quas ducimus blanditiis atque quibusdam, autem rerum, veniam, ullam voluptatibus tenetur aliquid! Quia voluptate autem reprehenderit debitis animi corporis ea suscipit adipisci voluptatibus?
            Quae aliquid sequi, quis harum iure dolores rem repellendus nesciunt illo nam beatae tempore necessitatibus praesentium explicabo placeat vitae eveniet voluptatum? Similique in dolorem, minima consequatur neque reprehenderit molestiae voluptas.
            Sapiente aperiam eligendi velit beatae adipisci deserunt assumenda delectus dignissimos voluptatum quae dolores praesentium blanditiis hic quidem, aspernatur harum tempora quos ducimus. Quis nesciunt deleniti illo deserunt. Non, sapiente inventore.
            Consectetur beatae necessitatibus, veniam nam neque quasi asperiores corporis doloribus perspiciatis? Placeat voluptate dolor, porro provident tempora officiis blanditiis tenetur quo! Voluptatibus, officia accusantium quae maiores asperiores officiis ex expedita.
            Alias ratione officiis reprehenderit tempora facere fugiat, minus, laborum perferendis soluta, ea magnam corporis repellat quo nostrum. Modi voluptatum esse quod dolorum culpa fugiat, beatae cupiditate nesciunt quibusdam, neque aperiam?
            Obcaecati quibusdam quos possimus illum! Deleniti, enim quam molestias corrupti cupiditate magni error perferendis, nostrum aut odio, possimus dolorem natus! Accusantium expedita, magni unde cupiditate doloremque odit illum commodi neque.
            Aspernatur eos commodi nobis atque vel optio aut repudiandae, amet nesciunt exercitationem minima nam voluptates rerum incidunt enim eligendi odio unde architecto doloribus pariatur quasi modi neque corporis. Deleniti, illo.
            Deserunt voluptate obcaecati cum omnis, officia illo harum enim quia impedit dolor doloribus aperiam perspiciatis laborum atque, rerum nam! A eaque exercitationem nesciunt adipisci debitis voluptatum? Et velit repellat quam?
            Ex error magni minima, eaque nulla accusamus dolor quia perspiciatis aut consequuntur, aliquid in voluptas beatae possimus itaque quo nemo delectus cupiditate magnam saepe enim ducimus tempore? Consequatur, unde mollitia.
            Modi maxime reprehenderit cumque corrupti, laborum iste quae labore non, voluptates earum dolor, minima atque quis. Et, atque iste optio, quam ex est rem ab soluta tenetur ipsum, in quaerat!
            Unde tempore, fugit ducimus consequatur fuga mollitia hic perspiciatis maxime perferendis, adipisci harum voluptates? Atque possimus fugiat delectus nihil quis nesciunt doloribus quas asperiores, et repellendus laudantium, nulla illo inventore?
            Adipisci asperiores, voluptates doloribus qui fugiat repellat rem aliquam quam consequuntur perspiciatis in vitae, facere at eos eaque nam, velit numquam deleniti pariatur minus aperiam atque inventore et? Animi, provident.
            Consequuntur ipsam ipsa quod dicta expedita ipsum aperiam reprehenderit assumenda facere obcaecati omnis distinctio magni perferendis sapiente doloremque voluptas ad eum neque, aspernatur doloribus magnam. Enim recusandae quo assumenda molestiae.
            Excepturi sunt aspernatur velit quisquam mollitia, dolorem voluptatibus hic? Asperiores ab, accusamus nostrum repellat dolores quisquam ipsum deleniti natus suscipit architecto fugiat placeat! Amet dolore ex iste ab sed placeat.
            Ex tempora laboriosam a earum similique necessitatibus quo, animi reprehenderit quasi ratione ut impedit fugiat tempore inventore laudantium maiores illum totam possimus doloribus eius, minima facilis veritatis. Fugiat, consectetur. Illo.
            Corporis maiores totam dolores dicta odio. Possimus at rerum sunt pariatur quisquam accusamus modi optio cupiditate consequatur rem aliquam illum laudantium sapiente hic error amet perferendis aperiam tempora, deserunt voluptatibus.
            Aliquam facilis quos in ut dolorem iure aperiam fugiat nam corporis. Soluta enim ad eos laboriosam fugit deleniti? Fuga distinctio nam corporis accusamus doloribus quas dolores? Corrupti fugiat voluptatem quod?
            Amet quisquam sapiente veritatis corrupti sequi animi. Nemo deleniti voluptas facilis voluptate quasi minus repudiandae, esse dolor porro veritatis numquam quisquam ipsam laudantium assumenda ea ipsum! Quam maxime sit commodi?
            Culpa doloremque recusandae asperiores nihil quibusdam voluptatem dolorum vero fugiat enim odit vitae quasi totam fuga, eaque fugit? Excepturi repudiandae aspernatur expedita cum repellendus tempore velit. Nesciunt debitis maiores rerum.
            Reiciendis omnis obcaecati recusandae magnam, nostrum distinctio officia? Temporibus sapiente consequatur in animi odio earum officia est adipisci aspernatur maiores, exercitationem nobis architecto eveniet explicabo quae dolorem, itaque soluta. Tempora?
        </div>
    )
}

export default Baitap6
