import React, { Suspense } from "react";
export default function LazyLoadComp() {
  return (
    <div className="p-6">
      <h1 className="text-2xl mb-4">Lazy Loading Demo</h1>
      <Suspense
        fallback={
          <div className="flex justify-center items-center h-40">
            <div className="h-20 w-20  bg-[#999999] flex items-center justify-center">
              <div className="animate-spin rounded-full border-4  h-10 w-10 border-white border-t-[#999999]"></div>
            </div>
          </div>
        }
      >
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae molestias a doloribus adipisci, consectetur atque repudiandae esse maxime labore quaerat! Nemo incidunt error et molestiae cum nostrum. Ea, expedita amet.
        Corrupti quidem eaque possimus, a ut alias vel tenetur error deserunt praesentium ipsa magnam qui porro nihil nulla similique rerum blanditiis consectetur laboriosam non provident odit iste quam. Dolor, mollitia.
        Quaerat officiis suscipit, unde id exercitationem reprehenderit itaque perferendis accusamus ea quae laudantium obcaecati quibusdam eius sed, tenetur, quis blanditiis! Laboriosam iure a cumque quae blanditiis eum corporis quam reprehenderit.
        Sequi porro provident voluptas quas impedit eos dolore ad ea expedita, corrupti minus commodi adipisci praesentium doloribus eum ex vitae dolorem a tempore. Laudantium, architecto ut dolor soluta ipsam distinctio!
        Commodi rerum necessitatibus repellendus, numquam nulla consequatur porro dignissimos animi? Quae repellat possimus obcaecati expedita incidunt assumenda unde iure molestias laborum in quo nesciunt, odit eaque, a beatae maiores temporibus.
        Deserunt nesciunt minus tenetur quibusdam quaerat, doloremque, expedita eligendi voluptatem illo ex odit impedit pariatur! Ipsa, eos ratione modi temporibus molestias corporis unde ut esse cumque libero, illo dignissimos sapiente.
        Quasi minus quod nobis corporis non voluptatem incidunt ad maxime nihil, aut ab aliquam ducimus odio molestiae eveniet maiores quae a libero, in autem culpa modi. Mollitia earum culpa iste!
        Praesentium nobis veritatis molestias quas maxime deleniti quasi voluptate odio sequi labore cum maiores fuga impedit pariatur numquam vel animi, ab dolorem iure, eos est? Praesentium eum perspiciatis ab sequi?
        Error laudantium nulla laborum sint nobis aut id? Mollitia laboriosam voluptatum dolorem, voluptates, quas error sequi, aperiam libero suscipit saepe exercitationem deleniti esse fugiat eveniet! Nesciunt amet commodi est consequatur.
        Est similique quaerat laborum, iste maiores placeat veritatis nemo! Facilis veritatis labore quod, corrupti eos ea dolor voluptas dolores asperiores veniam nostrum necessitatibus cumque quam autem obcaecati non nemo reiciendis?
        Illo saepe harum quod commodi aliquam incidunt voluptatem explicabo non facere, delectus cum molestiae eaque provident quasi optio maiores est ipsam veniam expedita ab? Eligendi doloribus consequuntur beatae enim doloremque?
        Cupiditate, obcaecati voluptatem? Velit optio animi nulla, voluptas porro neque ratione fugiat, vel qui deserunt esse expedita. Ad, officiis! Corrupti dolorum illo fugit reiciendis velit deleniti quas, ea omnis similique.
        Minima, voluptate. Accusamus, temporibus optio laudantium, labore officiis quis possimus molestiae ab natus asperiores dolore corporis error, soluta dolorem quasi assumenda? Pariatur ipsa officiis nulla asperiores ullam incidunt, nihil quae.
        Ratione impedit atque error qui consequatur molestias amet laudantium doloribus, ipsum ducimus deserunt quae! Aut, impedit? Distinctio, soluta corrupti. Veritatis placeat voluptas odio tempore doloribus recusandae corporis quia repudiandae quis!
        Doloribus aspernatur autem repellat temporibus similique velit, consectetur culpa laboriosam. Vero, quibusdam molestiae possimus rem culpa incidunt quidem deserunt commodi similique cupiditate consequatur excepturi dolorum soluta cum eaque facilis nemo?
        Perferendis tempore nulla, quia optio temporibus inventore consequatur laboriosam labore accusamus, incidunt laudantium. Illo, architecto reprehenderit veniam ea exercitationem iste error. Mollitia aliquam molestiae assumenda delectus reiciendis nemo saepe in!
        Ex facilis porro ratione sunt culpa eos accusamus non eaque tempora tenetur eius, architecto explicabo enim numquam officiis nesciunt cum molestiae sed similique. Ad ipsam expedita eaque in, sit sunt.
        Commodi, possimus quas distinctio eum iure eius esse debitis hic optio consectetur ullam omnis ut aspernatur inventore corrupti laudantium. Assumenda aperiam hic odit error esse fugiat reiciendis eveniet eos suscipit.
        Excepturi necessitatibus, sunt tenetur, neque cupiditate molestias quas at veritatis aliquam esse distinctio saepe illo, animi debitis rem ad ratione? Placeat vitae eius inventore neque provident sit consequatur! Officia, commodi.
        Veniam hic debitis a. Ex, sapiente, amet laboriosam pariatur modi doloribus quod odio voluptate molestias nobis quos consectetur numquam tempore minima adipisci quae repudiandae quis deleniti eveniet? Tempora, velit quia?
        Eos expedita minima dignissimos reprehenderit pariatur harum esse culpa facere hic officiis quisquam assumenda vero explicabo eum veritatis praesentium quod deserunt distinctio, tempora molestiae? Magnam incidunt dolorem dignissimos debitis sit!
        Sapiente, earum doloribus placeat at exercitationem repellendus? Aperiam, cupiditate commodi ipsam obcaecati quam delectus. Consequuntur dolorum labore temporibus inventore, earum impedit? Magnam repellat cum necessitatibus mollitia et soluta assumenda cumque!
        Odit inventore, repellendus obcaecati dolor ducimus sapiente nam voluptas optio, quae repellat neque excepturi. Quasi quibusdam temporibus, aliquam delectus expedita inventore aut unde labore ipsa assumenda quis voluptates omnis exercitationem!
        Non consequuntur accusantium laborum rerum suscipit nisi quas repudiandae in tempore rem expedita, omnis ducimus architecto sit saepe quo vel voluptatibus ea nulla. Ut cum pariatur sunt incidunt iusto quae?
        Dolore nesciunt commodi itaque quis sunt hic harum inventore quo debitis veritatis molestias explicabo aspernatur repudiandae numquam nobis suscipit, error ipsum consectetur quidem amet. Necessitatibus labore animi excepturi nemo et.
        Dolorem sint nobis libero, incidunt exercitationem quos perspiciatis laborum sed eos? Aliquam quisquam nisi rerum. Nihil, dolorum? Nisi, iste asperiores vel incidunt aspernatur voluptatem sed. Aut saepe rem error deleniti!
        Incidunt dignissimos magnam optio quod, quidem nihil, in omnis veritatis atque nulla ipsa harum asperiores repudiandae ducimus cupiditate non minima temporibus tempore totam vel dolor modi, voluptatum corrupti eaque. Sint.
        Quos aliquid error voluptate reprehenderit ratione quas corrupti sapiente, amet tempore asperiores, magni molestiae mollitia nostrum officiis quaerat. Veritatis earum accusantium ut eos quasi commodi illum in molestias accusamus dolore!
        Libero repudiandae consequatur magni modi exercitationem sit rerum dicta, distinctio est necessitatibus vitae suscipit illum non at voluptas sunt dolore odio maiores tempora. Reiciendis ullam provident, obcaecati quaerat consequatur expedita.
        Magni distinctio consectetur deserunt similique rerum. Suscipit nulla ratione hic adipisci recusandae quis voluptatum porro a dolor omnis, nihil, ut voluptas nisi quisquam, doloribus debitis perferendis magni neque veritatis sapiente.
        Alias consequatur maiores earum, incidunt libero ut ipsum sint rem excepturi provident laborum porro vitae tempore voluptatum suscipit aspernatur deleniti eos repudiandae quae. Aliquid obcaecati quos deleniti perspiciatis aperiam dolore?
        Nulla nam iusto velit provident tempore, nisi impedit maiores quisquam, sapiente explicabo deleniti similique exercitationem iure enim et accusamus, sunt vero natus. Error perspiciatis alias accusantium quod beatae nesciunt eius.
        Repellat tempora sint ipsum rerum, eum, officiis voluptates iure quo quam sunt sapiente aliquam atque earum consequatur exercitationem laboriosam natus ex vitae pariatur necessitatibus reiciendis est. Esse nobis quas sit!
        Laborum in maiores magnam culpa, accusamus vero quod. Ex obcaecati sapiente magnam aliquam maxime veritatis excepturi alias atque hic dolorem non assumenda dolores molestias earum culpa minima sunt, eum quam.
        Harum magnam quae rem corporis nobis eos distinctio? Temporibus ex, quam quasi quaerat, odio repellendus fugit, vel ullam quas excepturi delectus saepe officiis placeat modi molestiae aspernatur deleniti provident natus.
        Atque nisi fuga explicabo! Dolore dolorem veritatis eligendi sit, vero tempora? Suscipit cumque quis ducimus possimus, iste itaque numquam vero tenetur porro aspernatur delectus assumenda consectetur sapiente, molestiae quaerat sit.
        Dignissimos obcaecati nobis sunt veniam, quo ipsa esse adipisci vero, tempora ad amet unde! Distinctio quod, quis repellendus officia aliquam corrupti suscipit fugit molestiae dignissimos consequatur sit dolor qui accusamus!
        Similique expedita eius quidem, autem a veniam tempora quis tenetur magni! Dolorum, laudantium. Corrupti possimus porro repellendus tempora, commodi excepturi repellat iure? Quidem minus esse optio modi suscipit, dignissimos obcaecati!
        Officiis fuga natus explicabo fugiat. Iusto laudantium vitae sed accusamus. Distinctio velit ducimus ipsa laboriosam quaerat? Corrupti ex tenetur possimus aliquid enim repudiandae sit saepe iste! Placeat ut quo minima.
        Delectus quisquam minima id ea sequi beatae incidunt accusantium aut aliquid? Facilis necessitatibus nemo debitis enim quod, deleniti quasi exercitationem ipsum architecto eum laudantium laborum, aliquam quae sapiente rerum quibusdam?
        Eius nisi rem voluptates veniam tempore perspiciatis et exercitationem, nesciunt perferendis esse officia ducimus consequatur blanditiis reprehenderit id, nihil consectetur molestiae ad. Architecto aut minus facere tenetur, pariatur quibusdam praesentium.
        Placeat harum cupiditate voluptatibus architecto eius expedita ut, id, laborum odio, ullam recusandae quod ipsa illum. Culpa suscipit reprehenderit eius excepturi omnis rem ullam impedit! Assumenda nesciunt distinctio vero itaque?
        Laboriosam aliquam, quis, odio ducimus ea, voluptatum quos omnis rem non accusamus eius expedita corporis? Cupiditate enim vitae in quod quisquam officiis sit, aliquid nobis laborum necessitatibus, optio repellendus nulla!
        Corporis quis saepe voluptatem facilis, tenetur dolorum in hic maxime laborum necessitatibus possimus aut dolore placeat labore et laudantium corrupti totam, nobis illum ipsum numquam rerum culpa voluptatibus quod. Mollitia!
        Asperiores, debitis ratione atque ducimus corrupti dolorem numquam quam repudiandae, facere saepe temporibus similique. Rerum aperiam aspernatur dolorem architecto quam minus ipsa hic vel, odio cum doloremque quisquam, laboriosam nesciunt?
        Vel fuga maiores, repellat dolores ipsam ex quod. Labore quo quasi quam dolores excepturi hic ea adipisci sed, voluptatum quod optio architecto iure, dolorum, officia facilis? Id, accusantium ab. Dolores.
        Veniam dolorem fugiat aliquam tenetur eius ipsa labore maiores rem magni quod ut quasi error perferendis distinctio sequi similique, vero nesciunt beatae atque ipsum dignissimos? Eveniet consequatur labore tempora odio.
        Facilis, enim veniam non corporis, laboriosam maxime officia incidunt perspiciatis velit accusantium nihil dicta obcaecati tenetur natus repellendus unde deserunt modi minus, reprehenderit numquam quam hic. Expedita labore officia ducimus?
        Nam facilis inventore veniam magni ad dolores fugit tenetur esse, impedit quia quod saepe vel. Rerum dolorum ipsam atque repellendus totam tempora neque impedit sit? Veritatis suscipit praesentium accusantium ad.
        Odit adipisci eveniet nobis esse, impedit veritatis amet enim pariatur excepturi ad molestiae dolor ea possimus atque ratione iusto similique, a error quas vero quos labore! Sint architecto nulla temporibus?
        Eum temporibus provident amet deleniti, voluptatum vel, obcaecati quae animi minima cum iure nostrum iste nulla fugit voluptas voluptatibus est. Voluptas magnam quam minus voluptates accusamus! Aut laboriosam porro quam?
        Commodi, ipsum dolorem! Saepe, facere. Minus libero reprehenderit ipsum harum ipsam rem itaque, commodi ducimus voluptates consectetur suscipit ipsa quia debitis accusamus, porro officia consequuntur odit non eos fuga. Veniam?
        Eligendi id hic quia, beatae autem nisi odio aut modi nam deserunt earum doloremque qui blanditiis sapiente aliquid minus. Labore asperiores consequuntur impedit velit doloremque modi tenetur veritatis dolorum soluta.
        Quisquam neque voluptate vitae asperiores cum quidem, dicta ut a hic dolorum repellendus adipisci vel. Nam laudantium autem sequi alias nisi quod eum sapiente pariatur molestiae. Quidem nisi sint voluptate.
        Praesentium rerum voluptatem neque iusto, numquam animi hic nam pariatur, vero tempore adipisci. Molestias incidunt, magni, commodi odio aut deleniti aspernatur ratione unde minima, amet fuga repudiandae odit provident dicta.
        Tempore totam rerum iste velit numquam amet id delectus doloremque possimus, explicabo in odit veniam accusantium quibusdam quaerat ex deserunt! Dolor voluptas perspiciatis repellat molestiae sit deserunt perferendis est excepturi!
        Voluptatibus accusamus odio enim quis, esse beatae voluptatum maiores? Ratione, ut. Veniam iusto eaque sed sint facere soluta. Nesciunt, voluptas fugit eum necessitatibus perferendis distinctio quasi id nobis! Aut, praesentium!
        Minima officiis facilis expedita, asperiores molestiae sapiente inventore labore nobis quod? Incidunt asperiores culpa aperiam, aspernatur pariatur voluptates tempore dolore consequuntur! Ratione aliquid illum dolorum porro, earum itaque incidunt maxime?
        Eaque quam quasi aspernatur atque minus laudantium, distinctio dignissimos, quia veritatis ut possimus dolore, praesentium temporibus unde. Eius tempore minima laudantium nihil dolorem? Quis possimus vel, cumque a iste ipsa.
        Beatae accusantium molestias, doloremque cum esse corrupti pariatur fuga doloribus quia asperiores, a iste animi odit corporis, quos consectetur? Ex laborum aspernatur consectetur! Dolore voluptatem laborum quae suscipit animi numquam.
        Possimus cum eos vero repellat omnis odit fuga, maiores tempore culpa accusamus laudantium neque illo dignissimos blanditiis maxime. Aspernatur ipsam quos asperiores non fugit nisi expedita ratione? Optio, repudiandae cupiditate?
        Dolorum sint neque impedit, excepturi ipsa aut odio asperiores minus et officia quisquam eius iste unde quis dignissimos nam fugit dolor totam temporibus perspiciatis! Doloribus dicta aut libero cumque? Asperiores.
        Amet temporibus, magni voluptatibus consectetur aut totam quos voluptas eaque in atque dolores. Obcaecati praesentium, consectetur iusto quaerat quod, consequuntur doloremque qui minus illo eveniet totam nulla fugiat, modi perspiciatis!
        Reprehenderit culpa consequatur tenetur fuga blanditiis error odio! Quasi ipsa aliquid, tenetur delectus voluptas iure nisi illo ex aspernatur odio. Impedit accusantium consectetur, eaque sint dicta eos rem obcaecati porro?
        Earum recusandae voluptas omnis aut voluptatem ipsum ad! Laboriosam minima accusamus dicta quos qui praesentium, tenetur ut dolor eaque ratione sint, cupiditate officia impedit atque exercitationem voluptatum quas at voluptatibus.
        Quia eum soluta odio earum eveniet deleniti expedita, error quae est exercitationem laboriosam provident atque hic nam ipsam, odit magnam sed quasi pariatur porro delectus voluptate dolore? Deleniti, voluptatum distinctio!
        Enim dolores et reprehenderit fugit incidunt quidem accusantium, perspiciatis eos saepe excepturi harum distinctio quaerat voluptates numquam. Nemo ipsa voluptatum magnam nesciunt cupiditate consequuntur quasi. Iusto quaerat iste adipisci minima.
        Nisi quia laboriosam qui est voluptatem, beatae voluptates culpa vero accusantium dolorem. Eligendi soluta sapiente commodi natus cum aliquam culpa itaque aut suscipit illo, atque sed corporis, placeat nobis dicta.
        Veniam, maiores consequatur. Asperiores, nemo? Nostrum, odit! Minima beatae ut esse odit consectetur repellat magnam facere, quos voluptatum, doloremque voluptate labore modi est alias perspiciatis totam quia. Veniam, animi ullam.
        Eaque, labore commodi explicabo voluptates eum reprehenderit suscipit, odit mollitia dolore facilis laborum fugiat, sapiente nostrum. Optio quod modi delectus, iure explicabo minima suscipit perferendis voluptates adipisci nesciunt, vel nam.
        Culpa quidem, officiis ratione alias ex, minima, consequuntur rem nulla debitis voluptatum exercitationem. Vitae excepturi adipisci porro iure cupiditate sunt nemo esse ipsa quia doloremque. Sint quibusdam assumenda vel eligendi?
        Itaque beatae, cupiditate alias consectetur iure eaque, possimus repudiandae eligendi quod ab, accusantium eum a nulla quasi unde? Autem fugiat atque obcaecati vel possimus, saepe debitis cupiditate quae voluptatum a?
        Architecto repellendus sequi ratione aliquid illo porro distinctio eum, explicabo libero, rem nemo hic accusantium facilis iusto nostrum enim pariatur eveniet possimus non iste. Delectus mollitia aliquid eos quod modi!
        Quaerat ad iure eos nihil dolorum? Culpa rerum natus tempora cupiditate dicta provident excepturi commodi reiciendis amet ipsum consequatur porro delectus illo velit aliquam, dolorem accusantium. Illo eligendi nobis recusandae!
        Enim sequi fugit obcaecati fuga tempore suscipit a! Ad exercitationem reprehenderit perspiciatis hic adipisci. Hic consequatur saepe, in nihil consectetur temporibus assumenda quam cum, excepturi similique deleniti ipsam natus dolore?
        Earum quam doloribus optio, non laborum voluptatum provident sequi et dignissimos sed consequatur, pariatur temporibus consectetur repudiandae. Id laborum consequatur obcaecati quibusdam, nihil harum alias explicabo maxime consectetur! Incidunt, officiis?
        Ab rerum, corporis eligendi veniam dignissimos temporibus deserunt quidem, eveniet quos pariatur, porro quas suscipit ullam neque magni magnam eum impedit blanditiis doloremque nobis laudantium dolor. Magnam accusamus pariatur nobis!
        Voluptatibus doloremque cupiditate architecto debitis iusto, laboriosam ad eaque quo dolor! Voluptatem, temporibus labore! Pariatur facilis ea iste tempore cupiditate doloribus atque? Odio vero eius, sint voluptate ut saepe officiis?
        Atque dolorem odio natus assumenda eum? Suscipit autem, nobis maxime earum, officia laboriosam asperiores consequatur quas temporibus rem inventore! Necessitatibus adipisci tempore quaerat perspiciatis nam iusto, sunt sequi quibusdam placeat.
        Saepe dignissimos eveniet sed repellat eaque earum cum repellendus sit rerum aliquid ipsam similique expedita explicabo rem, corporis tempora debitis? Cum, quam. Reprehenderit voluptatem autem nemo corporis, temporibus laudantium non!
        Dolorum odit architecto harum, ipsa quibusdam repellendus omnis error sequi minus atque optio distinctio veritatis delectus autem amet pariatur non hic quos labore quasi quam laudantium fugit, sunt magni! Saepe!
        Iusto tempore unde velit, quibusdam, eveniet illum facere temporibus ducimus nemo, minima dolore ex sint dolor quae sunt? Doloremque quod recusandae beatae laudantium architecto consequuntur reiciendis sequi! Voluptas, at nisi?
        Consequuntur, nobis, reiciendis illo tempora, corporis sit sint quia similique veniam error quibusdam eligendi molestiae ut quos. Exercitationem doloremque saepe a alias, modi at iusto quas dolorum deleniti eveniet recusandae!
        Officia molestiae voluptas fugit quae iste rerum a asperiores praesentium, mollitia at, possimus deleniti id cupiditate laborum? Maiores excepturi iste blanditiis quisquam assumenda! Accusamus fugiat, qui illo quas ratione dolore!
        Aspernatur ut accusantium quidem nostrum veniam cumque a vero nam, dolor vel voluptates ea fugiat sequi possimus necessitatibus harum natus aperiam! Molestias ipsa tenetur aliquid, deleniti fugit quisquam quia esse.
        Eos quo aperiam magnam! Maiores eveniet in quo consequuntur voluptatibus libero fugiat nobis, quod omnis commodi excepturi tenetur autem ut corporis sequi, aperiam nisi consectetur accusantium nesciunt officia vitae repellat?
        Sequi harum enim placeat voluptatum facere ducimus eos animi itaque accusamus dolor nesciunt voluptate soluta ad, rerum, atque esse quaerat quae quas, tempore doloribus sapiente asperiores. Fugit quasi fuga nesciunt.
        Sequi aliquid ex placeat quidem odit. Eum ipsum temporibus numquam? Et reiciendis officiis aspernatur quae delectus id accusantium excepturi nesciunt. Quis molestias magni iure eos amet asperiores, quam architecto omnis.
        Error eveniet ab facilis. Ullam ipsam suscipit, at voluptatibus eveniet temporibus harum incidunt aliquam quam obcaecati quo debitis fugiat impedit dolores perferendis odit deserunt modi animi magnam ducimus aspernatur perspiciatis!
        Culpa unde aliquam dolor accusamus mollitia ratione eligendi blanditiis necessitatibus. Rem, totam eum ipsam ut delectus eos in ducimus aut quos inventore ab, nostrum reprehenderit animi assumenda sit incidunt iusto.
        Minima dolorum numquam vel nam aspernatur incidunt labore maxime quos totam voluptatem eius autem eum tempore recusandae consequuntur, voluptatum nisi sit omnis sequi ipsam sed. Architecto, vitae dolorum? Sed, nemo.
        Incidunt tempore dolor consequatur ipsum molestiae! Quibusdam ad blanditiis repudiandae dolorum, non autem repellat consequuntur vel iste, atque asperiores sit, eius ipsum ab architecto laboriosam modi animi obcaecati a fugit.
        Ab, rerum debitis illo vero accusamus nemo similique maxime sunt consectetur excepturi perspiciatis quam quaerat commodi repellat esse aut quibusdam praesentium dolorum magni laborum maiores reprehenderit nisi repudiandae! Ipsum, modi!
        Nihil reiciendis, alias commodi a impedit veritatis, blanditiis neque velit fugiat autem explicabo modi. Sit aut ea dicta quas delectus molestiae quaerat! Iusto, alias aperiam aliquam repellendus ipsa dolores itaque.
        Amet quisquam ipsam a ipsum fugiat? Aliquid facere nulla omnis laborum necessitatibus beatae quos eligendi doloremque inventore dolor mollitia suscipit, asperiores itaque sequi officia. Reiciendis minus repellat nobis sequi cum.
        Minima dicta ipsam distinctio sapiente impedit beatae consequuntur, officiis quisquam laboriosam facere nemo quibusdam maxime! Amet magnam harum facilis laboriosam quo! Totam esse rerum maxime atque quasi quos, ab possimus.
        Sapiente et eius sit excepturi rem porro voluptas autem. Laudantium deserunt explicabo facilis laboriosam et vel, ab commodi dolores animi molestiae, vero facere in earum, voluptatem libero quas veritatis provident.
        Adipisci enim necessitatibus explicabo odio consequuntur voluptas. Voluptatem non exercitationem enim possimus repellendus illum dicta porro in. Ad placeat at accusantium molestiae, numquam, quidem cupiditate rem nisi omnis aliquam impedit?
        Harum exercitationem possimus, ex non quas, totam ut amet est eius, sunt neque doloribus nihil. Necessitatibus alias sit ipsa dignissimos odio recusandae non omnis adipisci itaque praesentium, magni, repellendus tempora.
        Commodi odit rem vero. Dolor quisquam dolorum perferendis consequuntur mollitia optio iusto officiis eaque voluptates distinctio eligendi atque dolores laboriosam beatae ratione nisi perspiciatis tempore itaque voluptatum molestiae, deleniti eveniet.</p>
      </Suspense>
    </div>
  );
}